// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wpm.Management.Api.Infraestructure;

#nullable disable

namespace Wpm.Management.Api.Infraestructure
{
    [DbContext(typeof(ManagementDbContext))]
    [Migration("20241117003053_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Management")
                .HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Wpm.Management.Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BreedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("SexOfPet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeightClass")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pets", "Management");
                });

            modelBuilder.Entity("Wpm.Management.Domain.Entities.Pet", b =>
                {
                    b.OwnsOne("Wpm.SharedKernel.Weight", "Weight", b1 =>
                        {
                            b1.Property<Guid>("PetId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Value")
                                .HasColumnType("TEXT");

                            b1.HasKey("PetId");

                            b1.ToTable("Pets", "Management");

                            b1.WithOwner()
                                .HasForeignKey("PetId");
                        });

                    b.Navigation("Weight");
                });
#pragma warning restore 612, 618
        }
    }
}
